type YjsConstsType = {
  readonly WS_READY_STATE_CONNECTING: 0;
  readonly WS_READY_STATE_OPEN: 1;

  readonly MESSAGE_SYNC: 0;
  readonly MESSAGE_AWARENESS: 1;

  readonly MESSAGE_DELETE_ACCOUNT: 10;
  readonly MESSAGE_CHANGE_USER_ID: 11;
  readonly MESSAGE_CHANGE_PASSWORD: 12;
  readonly MESSAGE_CHANGE_ADMIN_PASSWORD: 13;

  readonly MESSAGE_TEST: 20;
  readonly MESSAGE_TEST_CLOSE: 21;

  readonly PING_TIMEOUT: number;

  readonly UPDATES_LIMIT: number;
};

export const yjsConsts: YjsConstsType = {
  WS_READY_STATE_CONNECTING: 0,
  WS_READY_STATE_OPEN: 1,

  MESSAGE_SYNC: 0,
  MESSAGE_AWARENESS: 1,

  MESSAGE_DELETE_ACCOUNT: 10,
  MESSAGE_CHANGE_USER_ID: 11,
  MESSAGE_CHANGE_PASSWORD: 12,
  MESSAGE_CHANGE_ADMIN_PASSWORD: 13,

  MESSAGE_TEST: 20,
  MESSAGE_TEST_CLOSE: 21,

  PING_TIMEOUT: 30000,

  UPDATES_LIMIT: 50,
};
