export const yjsConsts = {
  WS_READY_STATE_CONNECTING: 0 as 0,
  WS_READY_STATE_OPEN: 1 as 1,

  MESSAGE_SYNC: 0 as 0,
  MESSAGE_AWARENESS: 1 as 1,

  MESSAGE_DELETE_ACCOUNT: 10 as 10,
  MESSAGE_CHANGE_USER_ID: 11 as 11,
  MESSAGE_CHANGE_PASSWORD: 12 as 12,
  MESSAGE_CHANGE_ADMIN_PASSWORD: 13 as 13,

  MESSAGE_TEST: 20 as 20,
  MESSAGE_TEST_CLOSE: 21 as 21,

  PING_TIMEOUT: 30000 as number,

  UPDATES_LIMIT: 50 as number,
};
