export const yjsConsts = {
  WS_READY_STATE_CONNECTING: 0,
  WS_READY_STATE_OPEN: 1,

  MESSAGE_SYNC: 0,
  MESSAGE_AWARENESS: 1,

  MESSAGE_DELETE_ACCOUNT: 10,
  MESSAGE_CHANGE_USER_ID: 11,
  MESSAGE_CHANGE_PASSWORD: 12,

  MESSAGE_TEST: 20,
  MESSAGE_TEST_CLOSE: 21,

  PING_TIMEOUT: 30000,

  UPDATES_LIMIT: 50,
};
