version: "3.8"
services:
  node-dev:
    container_name: node
    image: node:18
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/workspace:cached
    env_file:
      - ../.env.development
    command: /bin/sh -c "while sleep 1000; do :; done"
  pg-dev:
    container_name: pg
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: yjs_playground
    volumes:
      - "./docker-data/pg:/var/lib/postgresql/data"
      - "./docker-data/init-sql-files:/docker-entrypoint-initdb.d"
  redis-dev:
    container_name: redis
    image: redis:6.0.6
    command: redis-server
    ports:
      - "6379:6379"
