version: "3.8"
services:
  pg-dev:
    container_name: pg
    image: postgres:12
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: yjs_playground
    volumes:
      - "./docker-data/pg:/var/lib/postgresql/data"
      - "./docker-data/init-sql-files:/docker-entrypoint-initdb.d"
  redis-dev:
    container_name: redis
    image: redis:6.0.6
    command: redis-server
    ports:
      - "6379:6379"
